import type { Metadata } from "next";
import { Italianno, Philosopher } from "next/font/google";
import "./globals.css";
import styles from './styles.module.css';
import Header from "./components/Header";


const italianno = Italianno({
    subsets: ['latin'],
    variable: '--font-italianno',
    weight: "400"
});

const philosopher = Philosopher({
    subsets: ['latin'],
    variable: '--font-philosopher',
    weight: "400"
});

export const metadata: Metadata = {
  title: "The Wedding of Sebastian & Widyana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={styles.bgLayout + ` ${philosopher.variable} ${italianno.variable} font-sans`}>
            <Header />
            {children}
        </body>
    </html>
  );
}
