import type { Metadata } from "next";
import { Italianno, Philosopher } from "next/font/google";
import "./globals.css";
import styles from './styles.module.css';
import Header from "./components/Header";


const italianno = Italianno({
    subsets: ['latin'],
    variable: '--font-italianno',
    weight: "400"
});

const philosopher = Philosopher({
    subsets: ['latin'],
    variable: '--font-philosopher',
    weight: "400"
});

export const metadata: Metadata = {
  title: "The Wedding of Sebastian & Widyana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
            <link rel="apple-touch-icon" sizes="180x180" href="/icons/favicon/apple-touch-icon.png" />
            <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon/favicon-32x32.png" />
            <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon/favicon-16x16.png" />
            <link rel="shortcut icon" href="/icons/favicon/favicon.ico" />
        </head>
        <body className={styles.bgLayout + ` ${philosopher.variable} ${italianno.variable} font-sans`}>
            <Header />
            {children}
        </body>
    </html>
  );
}
